export const mutations = {
  START_LOADING: "START_LOADING",
  FINISH_LOADING: "FINISH_LOADING",
  SET_CURRENT_COMIC: "SET_CURRENT_COMIC",
  SET_CURRENT_COMIC_FAILED: "SET_CURRENT_COMIC_FAILED",
  SET_PREVIOUS_COMICS: "SET_PREVIOUS_COMICS",
  SET_PREVIOUS_COMICS_FAILED: "SET_PREVIOUS_COMICS_FAILED",
  SELECT_COMIC: "SELECT_COMIC",
  SELECT_COMIC_FAILED: "SELECT_COMIC_FAILED"
};
